/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUtilisateursRouteImport } from './routes/_authenticated/utilisateurs'
import { Route as AuthenticatedSauvegardesRouteImport } from './routes/_authenticated/sauvegardes'
import { Route as AuthenticatedRecettesRouteImport } from './routes/_authenticated/recettes'
import { Route as AuthenticatedRapportsRouteImport } from './routes/_authenticated/rapports'
import { Route as AuthenticatedFournisseursRouteImport } from './routes/_authenticated/fournisseurs'
import { Route as AuthenticatedDocumentationRouteImport } from './routes/_authenticated/documentation'
import { Route as AuthenticatedDepensesRouteImport } from './routes/_authenticated/depenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCaisseRouteImport } from './routes/_authenticated/caisse'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUtilisateursRoute =
  AuthenticatedUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSauvegardesRoute =
  AuthenticatedSauvegardesRouteImport.update({
    id: '/sauvegardes',
    path: '/sauvegardes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecettesRoute = AuthenticatedRecettesRouteImport.update({
  id: '/recettes',
  path: '/recettes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRapportsRoute = AuthenticatedRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFournisseursRoute =
  AuthenticatedFournisseursRouteImport.update({
    id: '/fournisseurs',
    path: '/fournisseurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentationRoute =
  AuthenticatedDocumentationRouteImport.update({
    id: '/documentation',
    path: '/documentation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepensesRoute = AuthenticatedDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaisseRoute = AuthenticatedCaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/caisse': typeof AuthenticatedCaisseRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depenses': typeof AuthenticatedDepensesRoute
  '/documentation': typeof AuthenticatedDocumentationRoute
  '/fournisseurs': typeof AuthenticatedFournisseursRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/recettes': typeof AuthenticatedRecettesRoute
  '/sauvegardes': typeof AuthenticatedSauvegardesRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/caisse': typeof AuthenticatedCaisseRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depenses': typeof AuthenticatedDepensesRoute
  '/documentation': typeof AuthenticatedDocumentationRoute
  '/fournisseurs': typeof AuthenticatedFournisseursRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/recettes': typeof AuthenticatedRecettesRoute
  '/sauvegardes': typeof AuthenticatedSauvegardesRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/caisse': typeof AuthenticatedCaisseRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/depenses': typeof AuthenticatedDepensesRoute
  '/_authenticated/documentation': typeof AuthenticatedDocumentationRoute
  '/_authenticated/fournisseurs': typeof AuthenticatedFournisseursRoute
  '/_authenticated/rapports': typeof AuthenticatedRapportsRoute
  '/_authenticated/recettes': typeof AuthenticatedRecettesRoute
  '/_authenticated/sauvegardes': typeof AuthenticatedSauvegardesRoute
  '/_authenticated/utilisateurs': typeof AuthenticatedUtilisateursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/caisse'
    | '/clients'
    | '/dashboard'
    | '/depenses'
    | '/documentation'
    | '/fournisseurs'
    | '/rapports'
    | '/recettes'
    | '/sauvegardes'
    | '/utilisateurs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/caisse'
    | '/clients'
    | '/dashboard'
    | '/depenses'
    | '/documentation'
    | '/fournisseurs'
    | '/rapports'
    | '/recettes'
    | '/sauvegardes'
    | '/utilisateurs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/caisse'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/depenses'
    | '/_authenticated/documentation'
    | '/_authenticated/fournisseurs'
    | '/_authenticated/rapports'
    | '/_authenticated/recettes'
    | '/_authenticated/sauvegardes'
    | '/_authenticated/utilisateurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/utilisateurs': {
      id: '/_authenticated/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AuthenticatedUtilisateursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sauvegardes': {
      id: '/_authenticated/sauvegardes'
      path: '/sauvegardes'
      fullPath: '/sauvegardes'
      preLoaderRoute: typeof AuthenticatedSauvegardesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recettes': {
      id: '/_authenticated/recettes'
      path: '/recettes'
      fullPath: '/recettes'
      preLoaderRoute: typeof AuthenticatedRecettesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapports': {
      id: '/_authenticated/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AuthenticatedRapportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fournisseurs': {
      id: '/_authenticated/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof AuthenticatedFournisseursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentation': {
      id: '/_authenticated/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof AuthenticatedDocumentationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depenses': {
      id: '/_authenticated/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof AuthenticatedDepensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caisse': {
      id: '/_authenticated/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof AuthenticatedCaisseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCaisseRoute: typeof AuthenticatedCaisseRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepensesRoute: typeof AuthenticatedDepensesRoute
  AuthenticatedDocumentationRoute: typeof AuthenticatedDocumentationRoute
  AuthenticatedFournisseursRoute: typeof AuthenticatedFournisseursRoute
  AuthenticatedRapportsRoute: typeof AuthenticatedRapportsRoute
  AuthenticatedRecettesRoute: typeof AuthenticatedRecettesRoute
  AuthenticatedSauvegardesRoute: typeof AuthenticatedSauvegardesRoute
  AuthenticatedUtilisateursRoute: typeof AuthenticatedUtilisateursRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCaisseRoute: AuthenticatedCaisseRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepensesRoute: AuthenticatedDepensesRoute,
  AuthenticatedDocumentationRoute: AuthenticatedDocumentationRoute,
  AuthenticatedFournisseursRoute: AuthenticatedFournisseursRoute,
  AuthenticatedRapportsRoute: AuthenticatedRapportsRoute,
  AuthenticatedRecettesRoute: AuthenticatedRecettesRoute,
  AuthenticatedSauvegardesRoute: AuthenticatedSauvegardesRoute,
  AuthenticatedUtilisateursRoute: AuthenticatedUtilisateursRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
